create table if not exists public.healthcheck (
  id bigint primary key,
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  room text not null,
  "user" text not null,
  text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.users (
  id text primary key,
  name text not null,
  room text not null,
  created_at timestamptz not null default now(),
  constraint users_room_name_unique unique (room, name)
);
